# Generated by Django 6.0.5 on 2026-05-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorschedule_options_and_more'),
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor_notes',
        ),
        migrations.AddField(
            model_name='report',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='bp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='temperature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
