# Generated by Django 6.0.5 on 2026-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_token_number_and_more'),
        ('doctors', '0002_remove_doctor_available_days_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_token_per_doctor_per_day',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date', 'appointment_time'), name='unique_doctor_slot'),
        ),
    ]
