# Generated by Django 6.0.5 on 2026-05-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_unique_token_per_doctor_per_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'token_number']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_slot',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
