# Generated by Django 6.0.5 on 2026-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day', 'start_time', 'end_time'), name='unique_doctor_schedule_slot'),
        ),
    ]
