# Generated by Django 6.0.5 on 2026-05-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
